import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacidad · Manual SAMUR" };

export default function PrivacyPage() {
  return <article className="mx-auto max-w-3xl space-y-6 px-4 py-8 leading-relaxed">
    <header><h1 className="text-3xl font-semibold">Privacidad</h1><p className="mt-2 text-muted-foreground">Manual SAMUR · Actualizado el 7 de septiembre de 2026</p></header>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Quién mantiene la aplicación</h2><p>Miguel Rosa Zazo mantiene esta adaptación independiente y no oficial del Manual de Procedimientos de SAMUR-Protección Civil. No representa a SAMUR-PC ni al Ayuntamiento de Madrid.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Datos locales</h2><p>La aplicación móvil no requiere cuenta. Las búsquedas se procesan en el dispositivo; los favoritos, procedimientos recientes, preferencias y paquetes descargados se almacenan localmente. No hay sincronización de estos datos entre dispositivos ni analítica publicitaria integrada. La web utiliza almacenamiento local y caché para sus preferencias y funciones disponibles sin conexión.</p><p>No introduzcas datos de pacientes ni información clínica identificable. La aplicación es una herramienta de consulta y no está diseñada para registrar historias clínicas.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Ubicación y mapas</h2><p>El móvil solicita permiso de ubicación al pulsar una acción que lo necesita. Se utiliza para centrar el mapa y calcular distancias en línea recta en el dispositivo. Puedes denegar o revocar el permiso en los ajustes del sistema y seguir consultando el directorio.</p><p>Los mapas online y sus descargas acceden a servicios cartográficos externos de CARTO y OpenStreetMap. Estas peticiones pueden comunicar la dirección IP y la zona del mapa solicitada al proveedor. Abrir una ubicación en otra aplicación de mapas utiliza las condiciones y permisos de esa aplicación.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Conexiones externas</h2><p>La consulta web, las comprobaciones de actualización y las descargas requieren conexiones al alojamiento de la aplicación en Vercel. Los proveedores reciben datos técnicos necesarios para atender las peticiones, como la dirección IP. Los enlaces al manual y los anexos externos acceden a los servicios del Ayuntamiento de Madrid. No se envían los favoritos o el historial local con las comprobaciones de contenido.</p><p>TestFlight y Google/Apple pueden tratar diagnósticos conforme a tus ajustes y a sus propias condiciones. Los informes que decidas enviar para soporte contienen la información que incluyas voluntariamente.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Control y contacto</h2><p>Puedes retirar el permiso de ubicación, borrar los datos de la aplicación desde las opciones del sistema o desinstalarla. En la web, borra los datos del sitio desde tu navegador. Para preguntas o solicitudes relacionadas con privacidad, utiliza la <Link className="underline" href="/soporte">página de soporte</Link>. No incluyas información sensible en incidencias públicas.</p></section>
  </article>;
}
