import SwiftUI

// MARK: - Hex initialiser

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r, g, b: Double
        switch hex.count {
        case 6:
            r = Double((int >> 16) & 0xFF) / 255
            g = Double((int >> 8) & 0xFF) / 255
            b = Double(int & 0xFF) / 255
        default:
            r = 1; g = 1; b = 1
        }
        self.init(red: r, green: g, blue: b)
    }
}

// MARK: - SAMUR design tokens

extension Color {
    // samurPrimary is auto-generated by Xcode from Assets.xcassets/SamurPrimary.colorset
    // (#4E62D6 light / #6E84F8 dark — periwinkle-indigo, matches web app)

    /// Alias kept for backwards-compatibility with existing code
    static let samurBlue = samurPrimary
    /// Neon yellow accent
    static let samurYellow = Color(hex: "#DFFF00")

    // Section semantic colours (match web Tailwind palette)
    static let sectionSVA      = Color(hex: "#EF4444") // red-500
    static let sectionSVB      = Color(hex: "#3B82F6") // blue-500
    static let sectionOper     = Color(hex: "#F59E0B") // amber-500
    static let sectionComm     = Color(hex: "#8B5CF6") // violet-500
    static let sectionAdmin    = Color(hex: "#64748B") // slate-500
    static let sectionPsycho   = Color(hex: "#10B981") // emerald-500
    static let sectionTecnicas = Color(hex: "#06B6D4") // cyan-500
}

// MARK: - Glass card modifiers

extension View {

    /// Liquid glass card — native glassEffect on iOS 26+, ultraThinMaterial below.
    /// `tint` adds a color wash over the glass (great for section-coloured cards).
    @ViewBuilder
    func samurGlassCard(cornerRadius: CGFloat = 12, tint: Color = .clear) -> some View {
        if #available(iOS 26, *) {
            self
                .overlay(
                    RoundedRectangle(cornerRadius: cornerRadius)
                        .fill(tint.opacity(0.07))
                )
                .glassEffect(.regular, in: RoundedRectangle(cornerRadius: cornerRadius))
        } else {
            self
                .background {
                    RoundedRectangle(cornerRadius: cornerRadius)
                        .fill(.ultraThinMaterial)
                        .overlay(
                            RoundedRectangle(cornerRadius: cornerRadius)
                                .fill(tint.opacity(0.07))
                        )
                }
                .overlay(
                    RoundedRectangle(cornerRadius: cornerRadius)
                        .strokeBorder(
                            LinearGradient(
                                colors: [.white.opacity(0.5), .white.opacity(0.08)],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            ),
                            lineWidth: 0.75
                        )
                )
                .shadow(color: .black.opacity(0.10), radius: 14, y: 5)
                .shadow(color: .black.opacity(0.04), radius: 2,  y: 1)
        }
    }

    /// Legacy alias — maps to samurGlassCard with no tint.
    func samurCard(cornerRadius: CGFloat = 12) -> some View {
        samurGlassCard(cornerRadius: cornerRadius)
    }

    /// Page-level gradient background — gives glass cards something to blur against.
    func samurPageBackground() -> some View {
        self.background(
            LinearGradient(
                colors: [
                    Color.samurPrimary.opacity(0.07),
                    Color.samurPrimary.opacity(0.03),
                    Color(.systemBackground)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
            .ignoresSafeArea()
        )
    }

    /// Spring scale-down on press — attach to any tappable element.
    func pressScale(_ scale: CGFloat = 0.97) -> some View {
        modifier(PressScaleModifier(scale: scale))
    }
}

// MARK: - Press scale modifier

struct PressScaleModifier: ViewModifier {
    let scale: CGFloat
    @GestureState private var isPressed = false
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    func body(content: Content) -> some View {
        content
            .scaleEffect((!reduceMotion && isPressed) ? scale : 1.0)
            .animation(
                reduceMotion ? .none : .spring(response: 0.28, dampingFraction: 0.6),
                value: isPressed
            )
            .simultaneousGesture(
                DragGesture(minimumDistance: 0)
                    .updating($isPressed) { _, state, _ in state = true }
            )
    }
}
